### ISSUE TITLE
unexpected output during activation

### ISSUE THREAD

**Issue by kalligator** [mgmartel/WP-InstantClick#2]
This might be a config or other plugin combination causing it because it only shows up in one of my tested websites. I've checked for any spare whitespace hanging around, I've tried reactivating many times but it always comes up: 

> The plugin generated 214 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by mgmartel** [comment]
This is strange. It's probably PHP giving a warning of sorts. What PHP version are you using? Also, can you check the source code of this site on the front end, and check if there are any warnings or errors there?

Ultimately, the way to figure it out is using a technique like [this one](http://thehungrycoder.com/wordpress/how-i-have-solved-the-the-plugin-generated-xxxx-characters-of-unexpected-output-during-activation-problem.html).

Let me know!

**Comment by kalligator** [comment]
Followed your advice wiith save_error function, I caught this:

> Warning: call_user_func_array() expects exactly 2 parameters, 1 given in /home/xxxxxx/public_html/wp-content/plugins/WP-InstantClick-master/class-wp-instantclick.php on line 30

Offending line:

> call_user_func_array( $callback );

PHP Version 5.4.28

**Comment by mgmartel** [comment]
Thanks @kalligator! That was a silly oversight. Fixed it now.
